### ISSUE TITLE
Fabric server 0.15.0, MC 1.20.1 failing to launch

### ISSUE THREAD

**Issue by T0pBun** [miyo6032/maelstrom-mod-invasions#110]
fabric server failing to launch. individually tested mods, server loads fine with all mods except for BOMB. as soon as BOMB is removed, starts just fine. crash log included. 
[latest.log](https://github.com/miyo6032/bosses-of-mass-destruction/files/13517692/latest.log)

**Comment by solonovamax** [comment]
Can reproduce on the client side, so this issue is not server-specific.
